project_id = "qpsoytsyrdgouqrgkura"

[functions.send-followup-reminders]
verify_jwt = false

[functions.send-intake-notification]
verify_jwt = false

[functions.send-appointment-reminders]
verify_jwt = false